import type { NextPage } from 'next'
import Head from 'next/head'
import { useState } from 'react'
import { Description } from '../components/Description'
import { FormCalculator } from '../components/FormCalculator'
import { Header } from '../components/Header'
import { Range } from '../components/Range'
import styles from '../styles/Home.module.css'




const Home: NextPage = () => {
  const [resCalc, setResCalc] = useState<number>(0)

  return (
    <div className={styles.container}>
      <Head>
        <title>Health Overview</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className='container mx-auto h-[92vh]  grid md:grid-cols-2  grid-cols-1'>
        <div className='self-center h-[92vh]'>
          <Description />
          <FormCalculator setResCalc={setResCalc} />
        </div>
        <div className='self-center'>
          <Range resCalc={resCalc} />
        </div>

      </main>

    </div>
  )
}

export default Home
